export const resume = {
  fa: {
    name: 'امیرمحمد احسانی',
    initials: 'AE',
    role: 'توسعه‌دهنده فرانت‌اند',
    kicker: 'دانشجوی مهندسی کامپیوتر · حل‌کننده مسئله',
    availability: 'آماده همکاری به‌عنوان کارآموز فرانت‌اند',
    intro: 'با React و JavaScript رابط‌های سریع، واکنش‌گرا و خوش‌ساخت می‌سازم و از تبدیل ایده‌های ساده به تجربه‌های واقعی وب لذت می‌برم.',
    nav: ['درباره من', 'مهارت‌ها', 'مسیر من', 'پروژه‌ها', 'تماس'],
    labels: { about: 'داستان من', skills: 'ابزارهایی که با آن‌ها می‌سازم', experience: 'یادگیری و دستاوردها', projects: 'منتخب کارهای من', contact: 'بیایید با هم کار کنیم', courses: 'دوره‌ها و آموزش‌ها' },
    stats: [['۱۲', 'مخزن عمومی'], ['رتبه ۱', 'مسابقه ICPC'], ['۶+', 'دوره تخصصی']],
    about: [
      'دانشجوی ترم چهار مهندسی کامپیوتر دانشگاه سمنان هستم و مسیر حرفه‌ای خودم را روی توسعه فرانت‌اند متمرکز کرده‌ام. تجربه ساخت پروژه‌های شخصی با React، JavaScript و Tailwind CSS را دارم و آموخته‌هایم را پیوسته در گیت‌هاب به محصول قابل مشاهده تبدیل می‌کنم.',
      'کسب رتبه اول مسابقه برنامه‌نویسی ICPC درون‌دانشگاهی، علاقه من به حل مسئله و تفکر الگوریتمی را جدی‌تر کرد. حالا به دنبال فرصتی هستم تا در کنار یک تیم حرفه‌ای، روی پروژه‌های واقعی کار کنم و با بازخورد مستمر سریع‌تر رشد کنم.',
    ],
    skillGroups: [
      ['هسته فرانت‌اند', ['HTML5', 'CSS3', 'JavaScript', 'React']], ['رابط کاربری', ['Tailwind CSS', 'Responsive UI', 'Dark Mode', 'Component UI']],
      ['React و ابزارها', ['React Hooks', 'State Management', 'Vite', 'Git']], ['برنامه‌نویسی', ['C++', 'Python', 'Kotlin', 'Algorithms']],
      ['همکاری و انتشار', ['GitHub', 'GitLab', 'Version Control', 'Deployment']], ['توانمندی‌ها', ['Problem Solving', 'Async JavaScript', 'Clean Code', 'English']],
    ],
    experience: [
      { title: 'کارشناسی مهندسی نرم‌افزار', company: 'دانشگاه سمنان', date: '۱۴۰۳ — اکنون', location: 'سمنان', points: ['دانشجوی ترم چهار مهندسی کامپیوتر با تمرکز بر توسعه نرم‌افزار و فرانت‌اند', 'تمرین مستمر مبانی برنامه‌نویسی، الگوریتم و ساختمان داده', 'توسعه پروژه‌های مستقل در کنار مسیر دانشگاهی'] },
      { title: 'رتبه اول مسابقه برنامه‌نویسی ICPC', company: 'مسابقه درون‌دانشگاهی - تیمی', date: 'دستاورد دانشگاهی', location: 'دانشگاه سمنان', points: ['حل مسائل الگوریتمی در محدودیت زمانی', 'تقویت تحلیل مسئله، کار تیمی و پیاده‌سازی راه‌حل با C++', 'کسب مقام نخست در رقابت درون‌دانشگاهی'] },
      { title: 'مسیر توسعه فرانت‌اند', company: 'یادگیری پروژه‌محور و گیت‌هاب', date: 'فعال و در حال رشد', location: 'مستقل', points: ['ساخت پروژه‌های React با معماری کامپوننتی و Hooks', 'طراحی رابط‌های واکنش‌گرا با Tailwind CSS و CSS', 'انتشار و به‌روزرسانی ۱۲ مخزن عمومی در GitHub'] },
    ],
    courses: [['React با Vite', 'تاپلرن'], ['Tailwind CSS', 'فرادرس'], ['Asynchronous JavaScript', 'مکتب‌خونه'], ['HTML, CSS و JavaScript پروژه‌محور', 'مکتب‌خونه'], ['توسعه اندروید با Kotlin', 'مکتب‌خونه'], ['مبانی C++ - دوره ۶ ماهه', 'مجتمع فنی تهران']],
    projects: [
      { index: '۰۱', title: 'فروشگاه پوشاک', type: 'React · E-commerce', description: 'فروشگاه ساده React با فهرست محصولات و مسیر جداگانه برای مشاهده جزئیات هر محصول؛ تازه‌ترین پروژه عمومی من.', stack: ['React', 'JavaScript', 'Routing'], link: 'https://github.com/Luppin-1/fashion-store-react' },
      { index: '۰۲', title: 'مدیریت وظایف', type: 'React · Productivity', description: 'اپلیکیشن Todo با ساختار کامپوننتی، React Hooks و مدیریت State؛ ساخته‌شده با Vite و Tailwind CSS.', stack: ['React', 'Vite', 'Tailwind'], link: 'https://github.com/Luppin-1/Todo-app-react' },
      { index: '۰۳', title: 'صفحه ورود', type: 'React · UI', description: 'پیاده‌سازی یک رابط ورود تمیز، واکنش‌گرا و قابل توسعه با تمرکز بر ساختار فرم و تجربه کاربری.', stack: ['React', 'Vite', 'Tailwind'], link: 'https://github.com/Luppin-1/Login-project-react' },
      { index: '۰۴', title: 'وب‌سایت رستوران', type: 'Landing Page', description: 'لندینگ رستوران با طراحی واکنش‌گرا و تعاملات کاربری؛ پیاده‌سازی‌شده با فناوری‌های خالص وب.', stack: ['HTML', 'CSS', 'JavaScript'], link: 'https://github.com/Luppin-1/Restuarant' },
      { index: '۰۵', title: 'تمرین الگوریتم', type: 'Problem Solving', description: 'مجموعه تمرین‌های الگوریتمی برای تقویت حل مسئله و آماده‌سازی مسابقات برنامه‌نویسی.', stack: ['C++', 'Algorithms', 'ICPC'], link: 'https://github.com/Luppin-1/algorithm-practice' },
      { index: '۰۶', title: 'آزمایشگاه مینی‌پروژه‌ها', type: 'JavaScript Labs', description: 'مجموعه‌ای از تجربه‌های کوچک شامل منوی راست‌کلیک، بازی اعداد، لودینگ و تغییر تم روشن و تیره.', stack: ['JavaScript', 'CSS', 'UI Motion'], link: 'https://github.com/Luppin-1?tab=repositories' },
    ],
    marquee: ['React', 'JavaScript', 'Tailwind CSS', 'Vite', 'GitHub', 'C++', 'Problem Solving', 'Responsive Design'],
    contactText: 'اگر برای یک موقعیت کارآموزی فرانت‌اند، همکاری روی پروژه یا گفت‌وگو درباره یک ایده دنبال نیروی مشتاق و پیگیر هستید، خوشحال می‌شوم با شما صحبت کنم.',
    contact: [['ایمیل', 'amir85.ehsani12@gmail.com', 'mailto:amir85.ehsani12@gmail.com'], ['گیت‌هاب', 'github.com/Luppin-1', 'https://github.com/Luppin-1'], ['تلگرام', '@AmirMohammad_Ehsani', 'https://t.me/AmirMohammad_Ehsani'], ['موقعیت', 'سمنان، ایران', null]],
  },
  en: {
    name: 'AmirMohammad Ehsani', initials: 'AE', role: 'Front-end Developer', kicker: 'Computer Engineering Student · Problem Solver',
    availability: 'Open to front-end internship opportunities', intro: 'I build fast, responsive and thoughtfully crafted interfaces with React and JavaScript — turning simple ideas into tangible web experiences.',
    nav: ['About', 'Skills', 'Journey', 'Projects', 'Contact'],
    labels: { about: 'My story', skills: 'Tools I build with', experience: 'Learning and achievements', projects: 'Selected work', contact: "Let's work together", courses: 'Courses & training' },
    stats: [['12', 'Public repositories'], ['1st', 'ICPC competition'], ['6+', 'Technical courses']],
    about: ['I am a fourth-semester Computer Engineering student at Semnan University, focused on front-end development. I build personal projects with React, JavaScript and Tailwind CSS, consistently turning what I learn into visible work on GitHub.', 'Winning first place in an internal ICPC programming competition deepened my interest in problem solving and algorithmic thinking. I am now looking for an opportunity to contribute to real products, learn from a professional team and grow quickly through feedback.'],
    skillGroups: [
      ['Front-end core', ['HTML5', 'CSS3', 'JavaScript', 'React']], ['Interface design', ['Tailwind CSS', 'Responsive UI', 'Dark Mode', 'Component UI']],
      ['React & tooling', ['React Hooks', 'State Management', 'Vite', 'Git']], ['Programming', ['C++', 'Python', 'Kotlin', 'Algorithms']],
      ['Collaboration', ['GitHub', 'GitLab', 'Version Control', 'Deployment']], ['Strengths', ['Problem Solving', 'Async JavaScript', 'Clean Code', 'English']],
    ],
    experience: [
      { title: 'B.Sc. in Software Engineering', company: 'Semnan University', date: '2024 — Present', location: 'Semnan, Iran', points: ['Fourth-semester Computer Engineering student focused on software and front-end development', 'Continuous practice in programming fundamentals, algorithms and data structures', 'Building independent products alongside academic studies'] },
      { title: '1st Place - ICPC Programming Contest', company: 'Internal university team competition', date: 'Academic achievement', location: 'Semnan University', points: ['Solved algorithmic problems under time constraints', 'Strengthened analytical thinking, teamwork and C++ implementation', 'Ranked first in the internal university contest'] },
      { title: 'Front-end Development Track', company: 'Project-based learning and GitHub', date: 'Active and growing', location: 'Independent', points: ['Built React projects using component architecture and Hooks', 'Designed responsive interfaces with Tailwind CSS and vanilla CSS', 'Published and maintained 12 public GitHub repositories'] },
    ],
    courses: [['React with Vite', 'TopLearn'], ['Tailwind CSS', 'Faradars'], ['Asynchronous JavaScript', 'Maktabkhooneh'], ['Project-based HTML, CSS & JavaScript', 'Maktabkhooneh'], ['Android with Kotlin', 'Maktabkhooneh'], ['C++ Fundamentals - 6 months', 'Tehran Technical Complex']],
    projects: [
      { index: '01', title: 'Fashion Store', type: 'React · E-commerce', description: 'A React storefront featuring a product collection and dedicated detail routes — my most recent public project.', stack: ['React', 'JavaScript', 'Routing'], link: 'https://github.com/Luppin-1/fashion-store-react' },
      { index: '02', title: 'Todo App', type: 'React · Productivity', description: 'A component-driven task manager using React Hooks and state, built with Vite and Tailwind CSS.', stack: ['React', 'Vite', 'Tailwind'], link: 'https://github.com/Luppin-1/Todo-app-react' },
      { index: '03', title: 'Login Experience', type: 'React · UI', description: 'A clean, responsive and extensible login interface focused on form structure and user experience.', stack: ['React', 'Vite', 'Tailwind'], link: 'https://github.com/Luppin-1/Login-project-react' },
      { index: '04', title: 'Restaurant Website', type: 'Landing Page', description: 'A responsive restaurant landing page with interactive UI, built using the core web platform.', stack: ['HTML', 'CSS', 'JavaScript'], link: 'https://github.com/Luppin-1/Restuarant' },
      { index: '05', title: 'Algorithm Practice', type: 'Problem Solving', description: 'A growing collection of algorithm exercises for strengthening problem-solving and contest skills.', stack: ['C++', 'Algorithms', 'ICPC'], link: 'https://github.com/Luppin-1/algorithm-practice' },
      { index: '06', title: 'Mini Projects Lab', type: 'JavaScript Labs', description: 'Small experiments including a context menu, number game, loading effects and a light/dark theme.', stack: ['JavaScript', 'CSS', 'UI Motion'], link: 'https://github.com/Luppin-1?tab=repositories' },
    ],
    marquee: ['React', 'JavaScript', 'Tailwind CSS', 'Vite', 'GitHub', 'C++', 'Problem Solving', 'Responsive Design'],
    contactText: 'If you are hiring a motivated front-end intern, collaborating on a project, or exploring an idea, I would love to hear from you.',
    contact: [['Email', 'amir85.ehsani12@gmail.com', 'mailto:amir85.ehsani12@gmail.com'], ['GitHub', 'github.com/Luppin-1', 'https://github.com/Luppin-1'], ['Telegram', '@AmirMohammad_Ehsani', 'https://t.me/AmirMohammad_Ehsani'], ['Location', 'Semnan, Iran', null]],
  },
}
